@startuml Reactor
class Reactor {
    handle_events()
    register_handler(h)
    remove_handler(h)
}

note right of Reactor::"handle_events()"
    select(hadnlers);
    foreach h in handlers loop
        h.handle_event(type)
end note

class Event_Handler {
    handle_event(type)
    get_handle()
}

class Select {
    select()
}

interface Handle

Reactor -down-> Event_Handler : handlers
Reactor -left-> Select : uses
Select -down-> Handle: notifies
Event_Handler -left->Handle: owns
@enduml